using System.Threading;
using System.Threading.Tasks;
using MappingWithMediatr.ServiceA.AutoGenerated;
using MediatR;

namespace MappingWithMediatr.ServiceA.MappingHandlers
{
    public class ResponseAHandler : IRequestHandler<ResponseA, ResponseModel>
    {
        public Task<ResponseModel> Handle(ResponseA request, CancellationToken cancellationToken)
        {
            var response = new ResponseModel
            {
                Id = request.Id,
                Description = request.Description
            };

            return Task.FromResult(response);
        }
    }
}