using System.Threading.Tasks;
using MediatR;

namespace MappingWithMediatr.ServiceB
{
    public class SomeServiceB : IService
    {
        private readonly IMediator _mediator;

        public SomeServiceB(IMediator mediator)
        {
            _mediator = mediator;
        }
        
        public async Task<ResponseModel> GetResponseModel()
        {
            var customResponse = new AutoGenerated.ResponseB
            {
                Id = 2,
                Description = nameof(SomeServiceB)
            };

            return await _mediator.Send(customResponse);
        }
    }
}