namespace MappingWithMediatr.ServiceB.AutoGenerated
{
    /// <summary>
    /// A DTO that cannot be altered. Lets assume this is auto-generated from a swagger
    /// </summary>
    public partial class ResponseB 
    {
        public int Id { get; set; }
        public string Description { get; set; }
    }
}