namespace MappingWithMediatr.ServiceA.AutoGenerated
{
    /// <summary>
    /// A DTO that cannot be altered. Lets assume this is auto-generated from a swagger
    /// </summary>
    public partial class ResponseA
    {
        public int Id { get; set; }
        public string Description { get; set; }
    }
}