using System.Threading;
using System.Threading.Tasks;
using MappingWithMediatr.ServiceB.AutoGenerated;
using MediatR;

namespace MappingWithMediatr.ServiceB.MappingHandlers
{
    public class ResponseBHandler : IRequestHandler<ResponseB, ResponseModel>
    {
        public Task<ResponseModel> Handle(ResponseB request, CancellationToken cancellationToken)
        {
            var response = new ResponseModel
            {
                Id = request.Id,
                Description = request.Description
            };

            return Task.FromResult(response);
        }
    }
}