using System.Threading.Tasks;
using MappingWithMediatr.ServiceA.AutoGenerated;
using MediatR;

namespace MappingWithMediatr.ServiceA
{
    public class SomeServiceA : IService
    {
        private readonly IMediator _mediator;

        public SomeServiceA(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task<ResponseModel> GetResponseModel()
        {
            var customResponse = new ResponseA
            {
                Id = 1,
                Description = nameof(SomeServiceA)
            };

            return await _mediator.Send(customResponse);
        }
    }
}