using System.Threading;
using System.Threading.Tasks;
using MediatR;

namespace MappingWithMediatr.ServiceB.MappingHanlders
{
    public class ResponseBHandler : IRequestHandler<AutoGenerated.ResponseB, ResponseModel>
    {
        public Task<ResponseModel> Handle(AutoGenerated.ResponseB request, CancellationToken cancellationToken)
        {
            var response = new ResponseModel
            {
                Id = request.Id,
                Description = request.Description
            };

            return Task.FromResult(response);
        }
    }
}